### ISSUE TITLE
Create a Web Server for testing Demoing and Testing as a bot

### ISSUE THREAD

**Issue by blisscs** [blisscs/line-bot-sdk-elixir#5]
As to demonstrate and test our sdk we require a working demo that uses our library this to be created web server will be used for that purpose.

## Task List

- [x] Create a phoenix web server. Repo link: https://github.com/blisscs/elixir-line-bot-example
- [ ] Create a Url to receive a web hook
- [ ] add this library as an dependency
- [ ] Deploy to heroku

**Comment by blisscs** [comment]
Closing this.
Will do it seperately
